---
title: "accident"
lang: fr
date: ""
output:
  pdf_document:
    toc: false
  html_document:
    toc: true
    toc_float: true
---
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## R Markdown


On lit les données dans le tableau `df` de la manière suivante

```{r}
df = read.csv2("ONISR-2019.csv",sep=",")
head(df)
str(df)
```

## Including Plots

You can also embed plots, for example:

```{r}
df$S_sevérité <- (9*df$nb_tue+3*df$nb_hospitalise+df$nb_blesse)/13*100
max(df$nb_blesse)
max(df$nb_hospitalise)
max(df$nb_tue)
max(df$S_sevérité)
```

```{r}
df$lum   <- factor(df$lum)    # lumière : plein jour / nuit...
df$atm   <- factor(df$atm)    # météo
df$agg   <- factor(df$agg)    # hors agglo / en agglo
df$catr  <- factor(df$catr)   # type de route
df$circ  <- factor(df$circ)   # régime de circulation
df$col   <- factor(df$col)    # type de collision
df$surf  <- factor(df$surf)   # état de la chaussée
df$infra <- factor(df$infra)  # aménagement
df$situ  <- factor(df$situ)   # situation de l'accident
mod_complet <- lm(
 S_sevérité ~ vma + lum + atm + agg + catr + circ +
    col + surf + infra + situ +
    nb_velo + nb_moto + nb_voiture + nb_camion + nb_transport,
  data = df
)
summary(mod_complet)
```
```{r}
mod_simplifie <- step(mod_complet, direction = "both")
summary(mod_simplifie)
```

Note that the `echo = FALSE` parameter was added to the code chunk to prevent printing of the R code that generated the plot.
```{r}
View(df)
head(df)
```